### ISSUE TITLE
design a simple html webpage that displays list of our IC courses and upcoming assgnments

### ISSUE THREAD

**Issue by AnuragMaurya-PreD** [AnuragMaurya-PreD/netajikijai#5]
Also Send pending assignment to me. That has extra weightage for your contribution ;)

**Comment by Grypton** [comment]
Could you please elaborate more on this issue, what is to be done?

**Comment by AnuragMaurya-PreD** [comment]
nahi.jpg

**Comment by AnuragMaurya-PreD** [comment]
nahi.gif

**Comment by AnuragMaurya-PreD** [comment]
make a list of all our pending assignment deadlines in a html file 
you can add a css file to make it look haunting

**Comment by geetanshu12** [comment]
i want to do it..

**Comment by AnuragMaurya-PreD** [comment]
closing the issue
